language: java
env:
  global:
    - secure: cKHQ3fOT4xzkgZlcABWQNZtlCZNUYMBg5jmgFmprxxnjGO8n9odj9uVINtL2pJiyd2LsLyerN7Bt3JHxHWqviEOqP0JjT29R5zZV8t/8L0vQ7zJHJw9hvfer71H+cH/Ah4umRpMutoMJlzMjY4DtVz6XwYEeRCKm6ver70B567c=
before_script:
  - curl -L http://sourceforge.net/projects/saxon/files/Saxon-HE/9.5/SaxonHE9-5-1-4J.zip/download > SaxonHE9.zip
  - unzip SaxonHE9.zip
  - git config --global user.email "ci-server@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git config --global credential.helper "store --file=.git/credentials"


script:
  - java -jar saxon9he.jar -s:ucr-doc/wot-ucr.xml -o:wot-ucr-tmp.html -a

after_success:
  - git clone --branch gh-pages https://github.com/w3c/wot.git page
  - cp wot-ucr-tmp.html page/wot-ucr.html
  - cd page
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - git add wot-ucr.html
  - if [[ $TRAVIS_PULL_REQUEST == 'false' ]]; then git diff-index --quiet --cached HEAD || git commit -m"automated commit from Travis CI"; fi 
  - if [[ $TRAVIS_PULL_REQUEST == 'false' ]]; then git push https://github.com/w3c/wot.git gh-pages; fi 
